# Generated by Django 3.1.3 on 2020-12-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='username33',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
